class Screen_Constants:
    SCREEN_WIDTH = 480
    SCREEN_HEIGHT = 480

    GRID_SIZE = 20
    GRID_WIDTH = SCREEN_WIDTH / GRID_SIZE
    GRID_HEIGHT = SCREEN_HEIGHT / GRID_SIZE

    GRID_HEIGHT = int(GRID_HEIGHT)
    GRID_WIDTH = int(GRID_WIDTH)
    SCREEN_HEIGHT = int(SCREEN_HEIGHT)
    SCREEN_WIDTH = int(SCREEN_WIDTH)


    UP = (0 , 1)
    DOWN = (0 , -1)
    LEFT = (-1, 0)
    RIGHT = (1 , 0)
